### PR TITLE
Remove explicit MathOptInterface calls

### PR DESCRIPTION
**Pull request by odow**
@adow031 we should merge #28 first to check that this doesn't break things, but this is the preferred way to call things in MOI from JuMP.

### CODE REVIEW

**Comment by odow** [comment]
Ah. Now the CI is running.

**Comment by adow031** [comment]
Too many pull requests all at once. The system isn't used to there being so many things wrong with a package.

**Comment by odow** [comment]
There are a couple of scary things in the error message

I've never seen this before. Are you running `@eval using JuMP` or something?
```
WARNING: eval from module Main to JuDGE:    
Expr(:using, Expr(:., :JuMP))
  ** incremental compilation may be broken for this module **
```

The other issue is that you seem to be hard-coding `Int64` in places, instead of `Int`. (Which is `Int64` on 64-bit and `Int32` on 32-bit.)

**Comment by adow031** [comment]
I was going to change all the Int64s to Ints but since we all use 64bit I didn't bother.

In terms of the eval, as you can imagine most of the code is rooted in workarounds. In this case, I wanted to enable the user to write custom side constraints into the master. However, since the master problem is dynamically generated all the variables are anonymous. To make this seemless for the user, an eval is called to bring all the relevant master variables into the main scope with the appropriate names. These are removed once the user function is called.

Should I just accept all the pull requests and then fix the Int and test issues?

**Comment by adow031** [comment]
I'm not sure why the 64-bit cutting-stock tests failed, perhaps it's due to the random number generation. Should setting the seed lead to consistent random numbers regardless of the system?

**Comment by odow** [comment]
> Should setting the seed lead to consistent random numbers regardless of the system?

Nope :) You can use https://github.com/JuliaRandom/StableRNGs.jl, but this requires passing a random stream everywhere. 

I would fix the seed or fix the test.

**Pull request merged**
